version: '3.0'
services:
  rasa:
    image: rasa/rasa:latest-full
    ports:
      - 5005:5005
    volumes:
      - ./:/app
      - ./custom:/app/custom
    environment: 
      - PYTHONPATH=$PYTHONPATH:"D:\00000_Masterthesis\RasaXDocker\custom\ga_channel.py"
    command:
      - run
  action_server:
    image: rasa/rasa-sdk:latest
    volumes:
      - ./actions:/app/actions
    environment: 
      - PYTHONPATH=$PYTHONPATH:"D:\00000_Masterthesis\RasaXDocker\actions\actions.py"
  redis:
    image: redis:latest